// Color names generated by using this color analytics online tool
// https://www.color-blindness.com/color-name-hue/

export const midnightExpress = "#1F2633";
export const whiteSmoke = "#F5F5F5";
export const white = "#FFFFFF";
export const rhino = "#464D5C";
export const slateGrey = "#768091";
export const licorice = "#2F3845";
export const gainsboro = "#E3E3E3";
export const stormGrey = "#797A7D";
export const jaguar = "#252526";
export const lavender = "#E8F2FA";
export const lightSkyBlue = "#8ECAFA";
export const royalBlue = "#4384D9";
